"""Rule-family builders for Layer 1.

Known templates are still the most reliable path, but similar unknown games
can often be described by a stable rule family.  This module owns those
deterministic builders so Layer 1 can generate executable rules without
coupling callers to a specific game template name.
"""

from __future__ import annotations

import copy
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .external_frontend_reader import ExternalRuleInput
from .rule_parser import RuleParser

_RULES_DIR = Path(__file__).resolve().parent.parent / "rules"


@dataclass(frozen=True)
class RuleFamilySpec:
    """A parsed request for a supported rule family."""

    family_id: str
    game_id: str
    parameters: dict[str, Any]
    warnings: list[str]


class RuleFamilyBuilder:
    """Generate rules JSON for conservative, parameterized game families."""

    def __init__(self, *, rules_dir: Path | None = None, parser: RuleParser | None = None) -> None:
        self.rules_dir = rules_dir or _RULES_DIR
        self.parser = parser or RuleParser()

    def parse(self, *, rule_text: str, game_name: str | None = None) -> RuleFamilySpec | None:
        """Return a family spec if the text describes a supported game family."""
        normalized = RuleParser._normalize(" ".join(part for part in (game_name or "", rule_text) if part))
        if not self._looks_like_board_alignment(normalized, rule_text):
            return None

        params = self.parser.parse_grid_family_parameters(rule_text)
        return self._alignment_spec(
            family_id="board_alignment",
            game_id=self._game_id(game_name, rule_text),
            parameters=params,
            warnings=[],
            warn_on_missing=True,
        )

    def parse_external(self, rule_input: ExternalRuleInput) -> RuleFamilySpec | None:
        """Return a family spec from normalized external frontend input."""
        if rule_input.family == "board_alignment" or self._has_alignment_parameters(rule_input.parameters):
            return self._alignment_spec(
                family_id="board_alignment",
                game_id=rule_input.game_id or "generated_alignment_game",
                parameters=rule_input.parameters,
                warnings=list(rule_input.warnings),
                warn_on_missing=False,
            )
        return None

    def build(self, spec: RuleFamilySpec) -> dict[str, Any]:
        """Build an executable rules JSON from a rule-family spec."""
        if spec.family_id != "board_alignment":
            raise ValueError(f"unsupported rule family: {spec.family_id}")

        rules = self._load_alignment_base()
        params = spec.parameters
        rules["meta"] = {
            "gameId": spec.game_id,
            "version": "5.0.0",
            "description": "Generated by Layer1 board_alignment rule family",
            "family": spec.family_id,
        }
        rules["constants"]["board_size"] = params["board_size"]
        rules["constants"]["win_length"] = params["win_length"]
        rules["constants"]["vanish_probability"] = params["vanish_probability"]
        explicit = rules["chance"][0]["probability"]["explicit"]
        explicit[0]["prob"] = params["vanish_probability"]
        explicit[1]["prob"] = round(1.0 - params["vanish_probability"], 10)
        return rules

    def build_external(self, rule_input: ExternalRuleInput) -> tuple[dict[str, Any], RuleFamilySpec]:
        """Build rules JSON from a normalized external frontend input."""
        spec = self.parse_external(rule_input)
        if spec is None:
            raise ValueError("unsupported external rule family")
        return self.build(spec), spec

    def _load_alignment_base(self) -> dict[str, Any]:
        with open(self.rules_dir / "stochastic_gomoku.json", "r", encoding="utf-8") as f:
            return copy.deepcopy(json.load(f))

    @staticmethod
    def _alignment_spec(
        *,
        family_id: str,
        game_id: str,
        parameters: dict[str, Any],
        warnings: list[str],
        warn_on_missing: bool,
    ) -> RuleFamilySpec:
        board_size = parameters.get("board_size")
        win_length = parameters.get("win_length")
        if not isinstance(board_size, int):
            if warn_on_missing:
                warnings.append("未识别棋盘大小，使用 9x9")
            board_size = 9
        if not isinstance(win_length, int):
            if warn_on_missing:
                warnings.append("未识别连线胜利长度，使用 5 连")
            win_length = 5
        if board_size < 3:
            warnings.append("棋盘至少需要 3x3，已使用 3x3")
            board_size = 3
        if win_length < 3:
            warnings.append("连线胜利长度至少为 3，已使用 3")
            win_length = 3
        if win_length > board_size:
            warnings.append(f"连线长度 {win_length} 大于棋盘边长 {board_size}，已改为 {board_size}")
            win_length = board_size

        vanish_probability = parameters.get("vanish_probability", 0.0)
        if isinstance(vanish_probability, bool) or not isinstance(vanish_probability, int | float):
            vanish_probability = 0.0
        vanish_probability = float(vanish_probability)
        if vanish_probability < 0.0:
            warnings.append("消失概率不能小于 0.0，已使用 0.0")
            vanish_probability = 0.0
        if vanish_probability > 1.0:
            warnings.append("消失概率不能大于 1.0，已使用 1.0")
            vanish_probability = 1.0

        return RuleFamilySpec(
            family_id=family_id,
            game_id=game_id,
            parameters={
                "board_size": board_size,
                "win_length": win_length,
                "vanish_probability": vanish_probability,
            },
            warnings=warnings,
        )

    @staticmethod
    def _looks_like_board_alignment(normalized: str, rule_text: str) -> bool:
        family_hints = (
            "连珠",
            "连棋",
            "连子",
            "成线",
            "连线",
            "落子",
            "棋盘",
            "alignment",
            "connect",
            "in a row",
            "n-in-row",
        )
        has_hint = any(hint in normalized or hint in rule_text for hint in family_hints)
        has_board = RuleParser._extract_board_size(rule_text) is not None
        has_win = RuleParser._extract_win_length(rule_text) is not None
        return has_hint and (has_board or has_win)

    @staticmethod
    def _has_alignment_parameters(parameters: dict[str, Any]) -> bool:
        return "board_size" in parameters and "win_length" in parameters

    @staticmethod
    def _game_id(game_name: str | None, rule_text: str) -> str:
        raw = game_name or ""
        if not raw:
            match = re.search(r"([A-Za-z][A-Za-z0-9_-]{1,40})", rule_text)
            raw = match.group(1) if match else "generated_alignment_game"
        game_id = re.sub(r"[^a-zA-Z0-9_]+", "_", raw.strip().lower()).strip("_")
        return game_id or "generated_alignment_game"
